// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.corntree.milpa.fly.domain;

import com.corntree.milpa.fly.domain.AdminAccount;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AdminAccount_Roo_Configurable {
    
    declare @type: AdminAccount: @Configurable;
    
}
